const Projects = [
    "SpaceCraft Pro",
    "SpaceCraft Lite",
    "Customer Apt",
    "OrderWise",
    "SiteWise",
    "Nucleus Catalog System",
    "Valence Catalog System",
    "Data Platform",
    "HL Store",
    "Salesforce",
    "PixCraft",
    "AR Solutions",
    "SAP S/4 HANA",
    "DevOps",
    "Website",
    "HDS BAU",
    "HL Pronto",
    "Other (Management Tasks)",
    "Other (Miscellaneous)",
];
export default Projects;
